# Generated by Django 5.1.6 on 2025-02-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_colaborador_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='midia/img'),
        ),
    ]
