# Generated by Django 5.1.6 on 2025-02-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_myfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='texto',
        ),
    ]
